# -*- coding: utf-8 -*-
"""CG20261_Trabalho_2 - Rafael Manteiga Balbino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u85zANjvj-jwecWJOgddtN72ZrkTQ_bk

**UNIVERSIDADE DO ESTADO DO RIO DE JANEIRO**

**INSTITUTO DE MATEMÁTICA E ESTATÍSTICA - IME**

**COMPUTAÇÃO GRÁFICA (IME 04-10842)**

**DESCRIÇÃO:** Trabalho #2

**Importando Módulos do Python**
"""

import numpy as np # operações matemáticas e matriciais
from matplotlib import pyplot as plt # visualização dos gráficos e animações
from matplotlib import animation # funções de animação
from matplotlib import rc # para a definição de parâmetros de runtime configuration (rcParams)

"""**Entrada: objetos e valores iniciais**"""

# Objetos
po1 = np.array([[2.0,3.5,1],[1.4,2.8,1],[0.57,2.46,1],[1.05,1.69,1],[1.12,0.8,1],[2.0,1.0,1],[2.88,0.8,1],[2.95,1.7,1],[3.43,2.46,1],[2.6,2.8,1]])
po2 = np.array([[4.5,5.5,1],[4.2,5.0,1],[3.55,4.8,1],[4.02,4.35,1],[3.9,3.7,1],[4.5,4.0,1],[5.1,3.7,1],[5.0,4.35,1],[5.45,4.8,1],[4.8,4.9,1]])
po1 = np.transpose(po1)
po2 = np.transpose(po2)

# Valores iniciais
theta_r1 = 0.
theta_t1 = 0.
theta_r2 = 0.
theta_t2 = 0.
velocidade_r1 = 3.
velocidade_t1 = 3.
velocidade_r2 = 12.
velocidade_t2 = 6.

plt.figure(figsize=(5,5))
plt.xlim(-8, 8), plt.ylim(-8, 8)
x_list = np.append(po1[0,:], po1[0,0])
y_list = np.append(po1[1,:], po1[1,0])
plt.plot(x_list, y_list, "-b")
x_list = np.append(po2[0,:], po2[0,0])
y_list = np.append(po2[1,:], po2[1,0])
plt.plot(x_list, y_list, "-r")

"""**Definição da Função de Animação**"""

# configurando rcParams
rc('animation', html='jshtml')

# criando a figura
fig = plt.figure(figsize=(5,5))
ax = plt.axes()



# função de animação (executada a cada frame)
def animate(i):
    global po1, po2, theta_t1, theta_t2, theta_r1, theta_r2, velocidade_t1, velocidade_t2, velocidade_r1, velocidade_r2

    # gira os objetos em torno da origem
    dt = 0.5
    theta_t1 += velocidade_t1/30*dt
    cosseno = np.cos(theta_t1)
    seno = np.sin(theta_t1)
    R_origem = np.array([[cosseno, -seno, 0],
                         [seno,  cosseno, 0],
                         [0,  0, 1]])
    pt1 = np.matmul(R_origem, po1)
    pt2 = np.matmul(R_origem, po2)

    # gira o objeto #1 em torno do seu centro
    cx1 = np.mean(pt1[0,:])
    cy1 = np.mean(pt1[1,:])
    theta_r1 += velocidade_r1/30*dt
    cosseno = np.cos(theta_r1)
    seno = np.sin(theta_r1)

    T_ida1 = np.array([[1, 0, -cx1],
                      [0, 1, -cy1],
                      [0, 0, 1]])
    R_local1 = np.array([[cosseno, -seno, 0],
                        [seno,  cosseno, 0],
                        [0,     0,       1]])
    T_volta1 = np.array([[1, 0, cx1],
                        [0, 1, cy1],
                        [0, 0, 1]])

    M_local1 = np.matmul(T_volta1, np.matmul(R_local1, T_ida1))
    pt1 = np.matmul(M_local1, pt1)

    # gira o objeto #2 em torno do seu centro
    cx2 = np.mean(pt2[0,:])
    cy2 = np.mean(pt2[1,:])
    theta_r2 += velocidade_r2/30*dt
    cosseno = np.cos(theta_r2)
    seno = np.sin(theta_r2)

    T_ida2 = np.array([[1, 0, -cx2],
                      [0, 1, -cy2],
                      [0, 0, 1]])
    R_local2 = np.array([[cosseno, -seno, 0],
                        [seno,  cosseno, 0],
                        [0,     0,       1]])
    T_volta2 = np.array([[1, 0, cx2],
                        [0, 1, cy2],
                        [0, 0, 1]])

    M_local2 = np.matmul(T_volta2, np.matmul(R_local2, T_ida2))
    pt2 = np.matmul(M_local2, pt2)

    # gira o objeto #2 em torno do centro do objeto #1
    theta_t2 += velocidade_t2/30*dt
    cosseno = np.cos(theta_t2)
    seno = np.sin(theta_t2)
    T_ida_orb = np.array([[1, 0, -cx1],
                      [0, 1, -cy1],
                      [0, 0, 1]])
    R_orb = np.array([[cosseno, -seno, 0],
                      [seno, cosseno, 0],
                      [0, 0, 1]])
    T_volta_orb = np.array([[1, 0, cx1],
                            [0, 1, cy1],
                            [0, 0, 1]])
    M_orb = np.matmul(T_volta_orb, np.matmul(R_orb, T_ida_orb))
    pt2 = np.matmul(M_orb, pt2)

    # plota os objetos transformados
    ax.clear()
    ax.set_xlim(-8, 8), ax.set_ylim(-8, 8)

    x_list = np.append(pt1[0,:], pt1[0,0])
    y_list = np.append(pt1[1,:], pt1[1,0])
    ax.plot(x_list, y_list, "-b")

    x_list = np.append(pt2[0,:], pt2[0,0])
    y_list = np.append(pt2[1,:], pt2[1,0])
    ax.plot(x_list, y_list, "-r")

# cria animação
anim = animation.FuncAnimation(fig, animate, frames=90)

"""**Criação e Execução da Animação**"""

# Cria/executa animação
anim