# -*- coding: utf-8 -*-
"""CG20261_Trabalho_1 - Rafael Manteiga Balbino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAdwgfiR6BgVE1zY2zE-fdVmMT9PaiZv

**UNIVERSIDADE DO ESTADO DO RIO DE JANEIRO**

**INSTITUTO DE MATEMÁTICA E ESTATÍSTICA - IME**

**DESCRIÇÃO:** Trabalho #1 de Computação Gráfica (IME/UERJ)

---

#**0 - Instruções**

Neste trabalho só podem ser usadas as seguintes bibliotecas:

*   **Scikit-Image** ([`https://scikit-image.org/`](https://scikit-image.org/)): Processamento de imagens

*   **Scikit-Learn** ([`https://scikit-learn.org/`](https://scikit-learn.org/)): Machine Learning (possui algumas funções úteis para processamento de imagens)

*   **Matplotlib** ([`https://matplotlib.org/`](https://matplotlib.org/)): Gráficos

*   **Scipy** ([`https://www.scipy.org/`](https://www.scipy.org/)): É o pacote principal de rotinas científicas em Python

*   **Numpy** [`https://numpy.org/`](https://numpy.org/)): Análise numérica. É a principal biblioteca do Scipy
"""

from skimage import io # leitura e escrita de imagens
from skimage import data # banco de imagens
from skimage import exposure # manipulação de contraste
from skimage import util # utilidades
from skimage import filters # filtros
from skimage import color # conversão de cores
from scipy import ndimage # contém a operação de convolução (convolve) para a aplicação de filtros digitais
import matplotlib.pyplot as plt # visualização das imagens e histogramas
import numpy as np # operações matemáticas e matriciais

"""Além disso, você pode usar as imagens presentes no repositório (GitHub) indicado abaixo para os exercícios ou, se quiser, pode usar outras imagens que tenha carregado para o seu Google Drive."""

# Copiando as imagens do GitHub e salvando na pasta imagens_CG_UERJ, que será criada da raíz do disco virtual do Colab.
!git clone https://github.com/gilson-costa/imagens_CG_UERJ imagens_CG_UERJ

# Exibindo a lista de arquivos e imagens no disco virtual
!ls -R

"""#**Exercício 1**
1 - Leia uma imagem colorida (de 3 canais) e a apresente numa figura.

2 - Separe os canais da imagem colorida e apresente numa mesma figura as imagens monocromáticas correspondentes (primeira linha) e os respectivos histogramas com bins de 0 a 255 (segunda linha).

"""

# Lendo e apresentando a imagem colorida
papagaio = io.imread('/content/imagens_CG_UERJ/arara_full.png')
plt.imshow(papagaio)

# Separando os canais e apresentando as imagens monocromáticas (de cada canal) e histogramas correspondentes
plt.figure(figsize=(12,8))
canalum = papagaio[:,:,0]
plt.subplot(2,3,1)
plt.imshow(canalum,cmap='gray')
plt.subplot(2,3,4)
plt.hist(canalum.flatten(),bins=256)
canaldois = papagaio[:,:,1]
plt.subplot(2,3,2)
plt.imshow(canaldois,cmap='gray')
plt.subplot(2,3,5)
plt.hist(canaldois.flatten(),bins=256)
canaltres = papagaio[:,:,2]
plt.subplot(2,3,3)
plt.imshow(canaltres,cmap='gray')
plt.subplot(2,3,6)
plt.hist(canaltres.flatten(),bins=256)

"""
#**Exercício 2**
1 - Para a imagem usada no exercício anterior, calcule o negativo de cada canal individualmente e apresente numa mesma figura as imagens monocromáticas correspondentes (primeira linha) e os respectivos histogramas com bins de 0 a 255 (segunda linha).

2 - Combine (concatene) as os negativos dos canais da imagem original numa imagem tricromática e apresente a imagem colorida original e a negativa em uma única figura.

*Dica: para concatenar imagens monocromáticas use a função "np.stack".*"""

# Calculando os negativos dos canais e apresentando as imagens monocromáticas (de cada canal) e histogramas correspondentes
plt.figure(figsize=(12,8))
canalum = papagaio[:,:,0]
plt.subplot(2,3,1)
plt.imshow(255-canalum,cmap='gray')
plt.subplot(2,3,4)
plt.hist(255-canalum.flatten(),bins=256)
canaldois = papagaio[:,:,1]
plt.subplot(2,3,2)
plt.imshow(255-canaldois,cmap='gray')
plt.subplot(2,3,5)
plt.hist(255-canaldois.flatten(),bins=256)
canaltres = papagaio[:,:,2]
plt.subplot(2,3,3)
plt.imshow(255-canaltres,cmap='gray')
plt.subplot(2,3,6)
plt.hist(255-canaltres.flatten(),bins=256)

# Concatenando os negativos dos canais e apresentando a imagem colorida original e a negativa
original = np.stack((canalum, canaldois, canaltres), axis=2)
plt.figure(figsize=(12,8))
plt.subplot(2,3,5)
plt.imshow(original)
negativa = np.stack((255-canalum, 255-canaldois, 255-canaltres), axis=2)
plt.subplot(2,3,6)
plt.imshow(negativa)

"""#**Exercício 3**
0 - Utilize a imagem colorida leme.bmp, presente no repositório GitHub indicado na Introdução.

1 - Separe os canais da imagem e realize uma cooreção Gama, de forma a clarear as áreas escuras, sem saturar muito as intensidades dos pixels da áreas claras da imagem.

2 - Apresente em uma mesma figura os canais da imagem original (primeira linha) e os respectivos histogramas (segunda linha).

3 - Apresente em uma mesma figura os canais corrigidos (primeira linha) e os respectivos histogramas (segunda linha).

4 - Apresente em uma mesma figura a imagem colorida original e a imagem colorida produzida através da concatenação dos canais corrigidos.

*Dicas: para fazer a correção Gama, use a função "exposure.adjust_gamma"; para concatenar imagens monocromáticas use a função "np.stack".*
"""

# Lendo a imagem e apresentando as imagens dos canais e respectivos histogramas
leme = io.imread('/content/imagens_CG_UERJ/leme.bmp')

# Separando os canais e apresentando as imagens monocromáticas (de cada canal) e histogramas correspondentes
plt.figure(figsize=(12, 8))
canalum = leme[:,:,0]
plt.subplot(2,3,1)
plt.imshow(canalum,cmap='gray')
plt.subplot(2,3,4)
plt.hist(canalum.flatten(),bins=256)
canaldois = leme[:,:,1]
plt.subplot(2,3,2)
plt.imshow(canaldois,cmap='gray')
plt.subplot(2,3,5)
plt.hist(canaldois.flatten(),bins=256)
canaltres = leme[:,:,2]
plt.subplot(2,3,3)
plt.imshow(canaltres,cmap='gray')
plt.subplot(2,3,6)
plt.hist(canaltres.flatten(),bins=256)

# Aplicando a correção Gama sobre os canais e apresentando as imagens dos canais corrigidos e respectivos histogramas
lemegama = exposure.adjust_gamma(leme/255, gamma = 0.5)
plt.figure(figsize=(12, 8))
canalum = lemegama[:,:,0]
plt.subplot(2,3,1)
plt.imshow(canalum,cmap='gray')
plt.subplot(2,3,4)
plt.hist(canalum.flatten(),bins=256)
canaldois = lemegama[:,:,1]
plt.subplot(2,3,2)
plt.imshow(canaldois,cmap='gray')
plt.subplot(2,3,5)
plt.hist(canaldois.flatten(),bins=256)
canaltres = lemegama[:,:,2]
plt.subplot(2,3,3)
plt.imshow(canaltres,cmap='gray')
plt.subplot(2,3,6)
plt.hist(canaltres.flatten(),bins=256)

# Concatenando os canais corrigidos e apresentando a imagem colorida original e a corrigida
leme = io.imread('/content/imagens_CG_UERJ/leme.bmp')
plt.figure(figsize=(12,8))
plt.subplot(1,2,1)
plt.imshow(leme)
lemegama = np.stack((canalum, canaldois, canaltres), axis=2)
plt.subplot(1,2,2)
plt.imshow(lemegama)

"""#**Exercício 4**
0 - Utilize as imagens "moon" e "camera" do módulo "data" do Skimage e realize os procedimentos listados abaixo para rada uma delas.

1 - Realize o alargamento de contraste das imagens: saturando os pixels com
intensidades inferiores àquela que corresponde ao limite (percentil) de 2% (dos
pixels com intensidade mais baixa); e saturando os pixels com intensidades
superiores àquela que corresponde ao limite (percentil) de 98% (dos pixels com
intensidade mais alta).

2 - Realize a equalização de histograma das imagens.

3 - Apresente numa única figura para cada imagem: a imagem original e as imagens transformadas nos itens 1 e 2 (primeira linha); e os respectivos histogramas (segunda linha).

*Dicas: para calcular os percentis, use a função "np.percentile"; para fazer o alargamento de contraste, use a função "exposure.rescale_intensity"; para fazer a equalização de histogramas, use a função "exposure.equalize_hist".*
"""

# Lendo a imagem 'moon', realizando o alargamento de contraste e a equalização dos histogramas, e apresentando os histogramas
lua = data.moon()
plt.figure(figsize=(12,8))
plt.subplot(2,3,1)
plt.imshow(lua, cmap='gray')
plt.subplot(2,3,2)
luaalargada = exposure.rescale_intensity(lua, in_range=(np.percentile(lua,2), np.percentile(lua,98)))
plt.imshow(luaalargada, cmap='gray')
plt.subplot(2,3,3)
luaeqhist = exposure.equalize_hist(lua)
plt.imshow(luaeqhist, cmap='gray')
plt.subplot(2,3,4)
plt.hist(lua.flatten(), bins=256)
plt.subplot(2,3,5)
plt.hist(luaalargada.flatten(), bins=256)
plt.subplot(2,3,6)
plt.hist(luaeqhist.flatten(), bins=256)

# Lendo a imagem 'camera', realizando o alargamento de contraste a equalização dos histogramas, e apresentando os histogramas
camera = data.camera()
plt.figure(figsize=(12,8))
plt.subplot(2,3,1)
plt.imshow(camera, cmap='gray')
plt.subplot(2,3,2)
cameraalargada = exposure.rescale_intensity(camera, in_range=(np.percentile(camera,2), np.percentile(camera,98)))
plt.imshow(cameraalargada, cmap='gray')
plt.subplot(2,3,3)
cameraeqhist = exposure.equalize_hist(camera)
plt.imshow(cameraeqhist, cmap='gray')
plt.subplot(2,3,4)
plt.hist(camera.flatten(), bins=256)
plt.subplot(2,3,5)
plt.hist(cameraalargada.flatten(), bins=256)
plt.subplot(2,3,6)
plt.hist(cameraeqhist.flatten(), bins=256)

"""#**Exercício 5**
0 - Selecione duas imagens coloridas quaisquer (do repositório GitHub ou do seu Google Drive). Para este exercício é interessante que as imagens apresentem gamutes consideravelmente distintos.

1 - Realiza o pareamento de histograma entre as duas imagens: faça com que a primeira imagem tenha um histograma parecido com o da segunda, e vice-versa.

2 - Apresente em uma mesma figura as imagens coloridas originais (primeira linha) e as imagens transformadas (segunda linha).

*Dica: para fazer o pareamento de histogramas, use a função "exposure.match_histograms".*
"""

# Lendo as imagens, pareando histogramas e apresentando as imagens originais e com histogramas pareados
arara = io.imread('/content/imagens_CG_UERJ/arara_full.png')
pessoas = io.imread('/content/imagens_CG_UERJ/walkway.jpg')
plt.figure(figsize=(12,8))

araracanal3 = arara[:, :, :3]

histpareado1 = exposure.match_histograms(araracanal3,pessoas,channel_axis=2)
histpareado2 = exposure.match_histograms(pessoas,araracanal3,channel_axis=2)

plt.subplot(2,2,1)
plt.imshow(araracanal3)
plt.subplot(2,2,2)
plt.imshow(pessoas)
plt.subplot(2,2,3)
plt.imshow(histpareado1)
plt.subplot(2,2,4)
plt.imshow(histpareado2)

# Separando os canais das imagens originais e pareadas
araracanalum = arara[:,:,0]
araracanaldois = arara[:,:,1]
araracanaltres = arara[:,:,2]

pessoascanalum = pessoas[:,:,0]
pessoascanaldois = pessoas[:,:,1]
pessoascanaltres = pessoas[:,:,2]

histpareado3 = exposure.match_histograms(araracanalum,pessoascanalum)
histpareado4 = exposure.match_histograms(pessoascanalum,araracanalum)

histpareado5 = exposure.match_histograms(araracanaldois, pessoascanaldois)
histpareado6 = exposure.match_histograms(pessoascanaldois, araracanaldois)

histpareado7 = exposure.match_histograms(araracanaltres, pessoascanaltres)
histpareado8 = exposure.match_histograms(pessoascanaltres, araracanaltres)

plt.figure(figsize=(15, 10))

plt.subplot(2,3,1)
plt.imshow(araracanalum,cmap='gray')
plt.subplot(2,3,2)
plt.imshow(araracanaldois,cmap='gray')
plt.subplot(2,3,3)
plt.imshow(araracanaltres,cmap='gray')
plt.subplot(2,3,4)
plt.imshow(histpareado3,cmap='gray')
plt.subplot(2,3,5)
plt.imshow(histpareado5,cmap='gray')
plt.subplot(2,3,6)
plt.imshow(histpareado7,cmap='gray')

plt.figure(figsize=(15, 10))

plt.subplot(2,3,1)
plt.imshow(pessoascanalum,cmap='gray')
plt.subplot(2,3,2)
plt.imshow(pessoascanaldois,cmap='gray')
plt.subplot(2,3,3)
plt.imshow(pessoascanaltres,cmap='gray')
plt.subplot(2,3,4)
plt.imshow(histpareado4,cmap='gray')
plt.subplot(2,3,5)
plt.imshow(histpareado6,cmap='gray')
plt.subplot(2,3,6)
plt.imshow(histpareado8,cmap='gray')

"""#**Exercício 6**
0 - Selecione uma imagem monocromática qualquer. Observe que certas imagens monocromáticas, e.g., em formato PNG possuem três canas com intensidades idênticas. Neste caso deve-se extrair um dos canais para realizar o exercicio.

1 - Acrescente à imagem original ruído sal-e-pimenta, e apresente a imagem original e a imagem ruidosa em uma única figura.

2 - A aplique à imagem ruidosa os seguntes filtros: média; gaussiano; e mediana, e apresente numa mesma figura as imagens filtradas.

*Dicas: para introduzir ruído numa imagem, use a função "util.random_noise"; para fazer a filtragem com um filtro de média, use a função "ndimage.convolve"; para fazer a filtragem com um filtro Gaussiano, use a função "filters.gaussian"; para fazer a filtragem com um filtro de mediana, use a função "filters.rank.median".*
"""

# Lendo a imagem e acrescentando ruído, e mostrando as duas imagens
mulher = io.imread('/content/imagens_CG_UERJ/woman.png')
plt.figure(figsize=(12,8))

mulher = mulher[:,:,0]

mulherruidosp = util.random_noise(mulher,mode='s&p')
plt.subplot(1,2,1)
plt.imshow(mulher,cmap='gray')
plt.subplot(1,2,2)
plt.imshow(mulherruidosp,cmap='gray')

# Aplicando filtros e mostrando as imagens resultantes
mulherruidospmedia = ndimage.convolve(mulherruidosp,np.ones((3,3))/9)
mulherruidospgauss = filters.gaussian(mulherruidosp, sigma=1.5)
mulherruidospmediana = filters.rank.median(mulherruidosp)

plt.figure(figsize=(12,8))

plt.subplot(1,3,1)
plt.imshow(mulherruidospmedia,cmap='gray')
plt.subplot(1,3,2)
plt.imshow(mulherruidospgauss,cmap='gray')
plt.subplot(1,3,3)
plt.imshow(mulherruidospmediana,cmap='gray')

"""#**Exercício 7**
1 - Selecione uma imagem colorida qualquer e transforme-a em uma imagem monocromática.

2 - Suavize a imagem monocromática com um filtro Gaussiano.

3 - Calcule a magnitude e o ângulo do gradiente para cada pixel de uma imagem qualquer, utilizando os filtros de Sobel.

4 - Limiarize a imagem da magnitude, para mostrar apenas pontos de borda “fortes”. Defina o limiar empiricamente.

5 - Crie uma imagem colorida, colorindo cada ponto de borda de acordo com a direção/ângulo do gradiente:

*	Vermelho (ângulos próximos da horizontal): menor que 15 e maior que 345 graus; e entre 165 e 195 graus;

*	Amarelo (ângulos próximos da vertical): entre 75 e 105 graus; e entre 255 e 285 graus;

*	Verde (ângulos na diagonal direita): ntre 15 e 75 graus; e entre 195 e 255 graus;

*	Azul (ângulos na diagonal esquerda): entre 105 e 165 graus; e entre 285 e 345 graus.

6 - Mostre imagem original; a imagem com a magnitude do gradiente limiarizada (binária); e a imagem colorida de acordo com os ângulos do gradiente.

*Dicas: para a suavização com filtro Gaussiano, use a função "filters.gaussian"; para fazer a filtragem com um filtro de derivação, use a função "ndimage.convolve"; para calcular amplitudes e ângulos do gradiente, use as funções "np.sqrt", "np.square", e "np.arctan2".*

"""

# Lendo a imagem e transformando em monocromática, suavizando a imagem monocromática, mostrando a imagem colorida e a monocromática suavizada

# Carregando a imagem a ser processada

# Convertendo para um canal (tons de cinza)

# Exibindo as imagens

# Aplicando filtros de derivação (Sobel)

# Criando os filtros

# Calculando as derivadas parciais

# Calculando a aplitude do Gradiente

# Calculando a fase/ângulo do Gradiente

# Exibindo as imagens Gx, Gy, G_amp, G_ang

# Colorindo a imagem de ângulo por faixas

# entre -15o e 15o -> vermelho

# maior que 15o -> verde

# menor que 15o -> azul

# maior que 75o e menor que -75o -> amarelo

# maior que 105o -> azul

# menor que -75o -> verde

# maior que 165o e menor que -165o -> vermelho

# Exibindo as imagens de ângulo (tons de cinza e colorizada)

# Limiarizando a imagem de amplitude

# Limiarizando a imagem de ângulo

# Exibindo as imagens: original, amplitude do gradiente limiarizada, ângulo do gradiente limiarizada